image: archlinux
packages:
  - rustup
  - nodejs
sources:
  - https://git.sr.ht/~verfassungsblog/Verfassungsbooks-Rendering-Server
secrets:
  - 416fdee7-bb30-4fef-9a14-f0983a977006
environment:
  deploy: verfassungsbooks@138.201.174.17
tasks:
  - setup: |
      rustup default stable
  - build: |
      branch_name=$(echo $GIT_REF | rev | cut -d'/' -f1 | rev)
      cd Verfassungsbooks-Rendering-Server
      cargo build --release
  - packaging: |
      cd Verfassungsbooks-Rendering-Server
      mkdir packaged
      cp target/release/Verfassungsbooks-Rendering-Server packaged/
      mkdir packaged/config
      mkdir packaged/rendering-envs
      mkdir packaged/templates
      cp -R rendering-envs/* packaged/rendering-envs
      cp config/default.toml packaged/config/
      cd packaged && tar -vczf ../verfassungsbooks-rendering-server-bundled.tar.gz *
artifacts:
  - Verfassungsbooks-Rendering-Server/verfassungsbooks-rendering-server-bundled.tar.gz
triggers:
  - action: email
    condition: failure
    to: kd@verfassungsblog.de