bind_to_host = "[::]"
port = "6969"
ca_cert_path = "certs/root.crt"
client_cert_path = "certs/client.crt"
client_key_path = "certs/client.key"
revocation_list_path = "certs/crl.der"
temp_template_path = "templates"
# Number of rendering requests to be executed concurrently
max_rendering_threads = 10