name: Sync to SourceHut

on:
  push:
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
	fetch-depth: 0

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SOURCEHUT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa git.sr.ht >> ~/.ssh/known_hosts

    - name: Push to SourceHut
      run: |
        git remote add sourcehut git@git.sr.ht:~verfassungsblog/Verfassungsbooks-Rendering-Server
        git push sourcehut --force --all
